### ISSUE TITLE
HA throws an error of uncought exception see logger output

### ISSUE THREAD

**Issue by mannebk79** [wsdt/sensor.cryptoportfolio#3]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: root
Source: custom_components/cryptoportfolio/BTCPortfolioSensor.py:62
Integration: cryptoportfolio (documentation)
First occurred: 17:51:45 (12 occurrences)
Last logged: 18:46:31

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
  File "/config/custom_components/cryptoportfolio/BlockChainInfoQueue.py", line 32, in processQueue
    task.execute()
  File "/config/custom_components/cryptoportfolio/BTCPortfolioSensor.py", line 62, in execute
    self._state = int(data) / (10 ** self._decimals)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'dict'

**Comment by wsdt** [comment]
Looks like the BTC Api provider changed its API. 
Happy to merge it, if you want to upgrade to their current API.

**Comment by mod25** [comment]
@wsdt howto? same as ehterscan api? thank you
